In [1]:
import numpy as np

In [2]:
arr=np.arange(1,10)

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr[1:5]  #1. indeksten 5. indekse kadar olan değerleri bastırır. 5 indeksi bastırmaz.

array([2, 3, 4, 5])

In [8]:
arr[:3]  #0. indeksten 3. indekse kadar olan değerleri bastırır. 3. indeksi bastırmaz.

array([1, 2, 3])

In [9]:
arr[::2]    #Baştan sonra kadar 2 atlayarak gider.

array([1, 3, 5, 7, 9])

In [11]:
arr[::-1]  #Sondan geriye doğru bastırır

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [12]:
arr[:3]=25 #0. 1. ve 2. indeksteki değerleri 25 ile değiştirir

In [13]:
arr

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [18]:
arr2=arr.copy()

In [20]:
arr2 #Burada arr2 üzerinde işlem yaparsak arr etkilenmez. Ancak copy() olarak oluşturmasaydık arr2 ye yapacağımız değişiklik arr yi de etkileyecekti

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [21]:
newArray=np.arange(1,21)

In [22]:
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [25]:
newArray.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [27]:
newArray=newArray.reshape(5,4)

In [28]:
newArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [29]:
newArray[0,0]

1

In [30]:
newArray[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [31]:
newArray[:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
newArray[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
arr=np.arange(1,11)

In [34]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [38]:
booleanArray=arr>4
arr[booleanArray]

array([ 5,  6,  7,  8,  9, 10])

In [39]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])