In [1]:
data_list=[1,2,3]

In [2]:
data_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr=np.array(data_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
data_list2=[[10,20,30],[40,50,60],[70,80,90]]

In [7]:
arr2=np.array(data_list2)

In [9]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [10]:
arr3=np.array([1,2,3,4,5])

In [11]:
arr3

array([1, 2, 3, 4, 5])

In [12]:
arr3[0]

1

In [13]:
arr3[4]

5

In [14]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [15]:
arr2[2,2]

90

In [16]:
arr2[1,0]

40

In [18]:
arr2[2,5]

IndexError: index 5 is out of bounds for axis 1 with size 3

In [19]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
np.arange(0,100,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [21]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [23]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
np.ones((3,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [47]:
np.linspace(0,100,5)     #0-100 arasındaki değerleri 5 eşit parçaya bölerek bunları saklar. Hesaplamaya son değeri de dahil eder

array([  0.,  25.,  50.,  75., 100.])

In [51]:
np.linspace(0,1,9)

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

In [59]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [60]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [63]:
np.random.randint(10)   #0-10 arasında rastgele değer döner

9

In [65]:
np.random.randint(1,10,5)    # 1-10 arasında 5 tane değer üretti ve bunları array içinde depoladı.  

array([3, 1, 7, 5, 9])

In [67]:
np.random.rand(5)   #0-1 arasında 5 tane değeri depolayan array oluşturdu

array([0.6562093 , 0.62835471, 0.56226905, 0.9845358 , 0.32218012])

In [74]:
np.random.randn(5)  # 0 ın etrafonda gauss distribution değerleri oluşturdu. Bunun önemi - değerler de oluşabilmesi.

array([-0.60811009,  1.35788629, -0.36140465,  0.12164901,  0.1596355 ])

In [75]:
arr=np.arange(25)

In [76]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [77]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [78]:
newArray=np.random.randint(0,100,10)

In [79]:
newArray

array([47, 35, 27,  3, 25, 62,  1, 70, 55, 16])

In [80]:
newArray.max()

70

In [81]:
newArray.min()

1

In [82]:
newArray.sum()    #Tüm değerlerin toplamı

341

In [83]:
newArray.mean()    #Tüm değerlerin ortalaması

34.1

In [85]:
newArray.argmax()   #En büyük değerin indeksini verir

7

In [86]:
newArray.argmin()     #En küçük değerin indeksini verir

6

In [87]:
detArray=np.random.randint(1,100,25)

In [88]:
detArray

array([61, 77, 27, 67, 86, 52, 21, 10, 50, 68, 53, 31, 24, 78, 13, 56,  3,
       56, 84, 39, 73,  9, 44, 55, 48])

In [92]:
detArray=detArray.reshape(5,5)

In [93]:
detArray

array([[61, 77, 27, 67, 86],
       [52, 21, 10, 50, 68],
       [53, 31, 24, 78, 13],
       [56,  3, 56, 84, 39],
       [73,  9, 44, 55, 48]])

In [94]:
np.linalg.det(detArray)

-305552184.9999992

In [101]:
detArray2=np.array([[1,2],[3,4]])

In [102]:
detArray2

array([[1, 2],
       [3, 4]])

In [103]:
np.linalg.det(detArray2)

-2.0000000000000004

In [105]:
round(np.linalg.det(detArray2))

-2