In [2]:
import numpy as np

In [2]:
arr=np.array([1,1,1,1,1])

In [3]:
arr

array([1, 1, 1, 1, 1])

In [6]:
arr3=np.ones(5)

In [7]:
arr3

array([1., 1., 1., 1., 1.])

In [10]:
arr4=np.zeros(5)

In [11]:
arr4

array([0., 0., 0., 0., 0.])

In [5]:
den=np.arange(2,101,2)

In [6]:
den

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [8]:
er=np.array([10,10,10,10,10])

In [9]:
er

array([10, 10, 10, 10, 10])

In [128]:
np.ones(5)*10

array([10., 10., 10., 10., 10.])

In [16]:
at=np.arange(1,17)

In [17]:
at

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [18]:
at.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [129]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [139]:
np.random.rand()*5

2.183818915475293

In [140]:
np.random.randn(25).reshape(5,5)  #5x5 lik bir gauss distrubition dağılımlı bir tablo

array([[-0.23540449, -0.50145045,  1.1246379 ,  0.75652006, -0.51739104],
       [ 0.11091611, -0.56114664,  0.00312583, -0.09560345, -0.36901006],
       [ 0.18495999, -1.11633453, -0.15471228,  0.79745994, -1.37977169],
       [ 2.4891616 , -0.33942666,  0.54723034,  0.56166265,  1.03898975],
       [ 1.99083569, -0.33938296, -0.88187651,  0.92813612, -0.52531912]])

In [141]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [51]:
e=np.arange(1,101)
e=e.reshape(10,10)

In [52]:
e

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [53]:
e[5,4]

55

In [54]:
e[:3,:3]

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23]])

In [60]:
e[4:,:]

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [143]:
e[6:,4:]

array([[ 65,  66,  67,  68,  69,  70],
       [ 75,  76,  77,  78,  79,  80],
       [ 85,  86,  87,  88,  89,  90],
       [ 95,  96,  97,  98,  99, 100]])

In [147]:
e[:3,2:4]

array([[ 3,  4],
       [13, 14],
       [23, 24]])

In [149]:
e[:3,1]

array([ 2, 12, 22])

In [150]:
e[:3,1:2]

array([[ 2],
       [12],
       [22]])

In [100]:
e[:3,2]

array([ 3, 13, 23])

In [151]:
e[:10,9:10]

array([[ 10],
       [ 20],
       [ 30],
       [ 40],
       [ 50],
       [ 60],
       [ 70],
       [ 80],
       [ 90],
       [100]])

In [152]:
e[:10,9]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [121]:
arr1=((np.random.rand(9)*5).astype(int)).reshape(3,3)
arr2=((np.random.rand(9)*5).astype(int)).reshape(3,3)

In [122]:
arr1

array([[2, 3, 3],
       [1, 3, 0],
       [4, 4, 0]])

In [123]:
arr2

array([[0, 3, 1],
       [4, 4, 0],
       [2, 4, 2]])

In [124]:
arr1*arr2

array([[ 0,  9,  3],
       [ 4, 12,  0],
       [ 8, 16,  0]])

In [125]:
arr1.mean()

2.2222222222222223

In [126]:
arr1.sum()

20

In [127]:
arr1+arr2

array([[2, 6, 4],
       [5, 7, 0],
       [6, 8, 2]])