In [4]:
import numpy as np

In [5]:
arr1=np.array([10,20,30,40,50,60])
arr2=np.array([2,3,4,5,6,7])

In [6]:
arr1.mean()  #arr1 in ortalamasını alır

35.0

In [6]:
arr1+arr2    # Burada toplanan arrayler aynı boyutlarda olmalı yoksa hata alırız.

array([12, 23, 34, 45, 56, 67])

In [7]:
arr1-arr2

array([ 8, 17, 26, 35, 44, 53])

In [8]:
arr1*arr2

array([ 20,  60, 120, 200, 300, 420])

In [9]:
arr1/arr2

array([5.        , 6.66666667, 7.5       , 8.        , 8.33333333,
       8.57142857])

In [10]:
arr1+10

array([20, 30, 40, 50, 60, 70])

In [11]:
arr2 - 2

array([0, 1, 2, 3, 4, 5])

In [14]:
arr1 / 3

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667,
       20.        ])

In [16]:
np.sqrt(arr1)    #arr1 deki her elemanın karekökünü alır

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781,
       7.74596669])